export const projects = [{
    name: "Eibsee Hotel",
    projektart: "Komfort",
    url: "https://www.eibsee-hotel.de/",
    online: "08.01.2024",
    jahr: "2024",
    img: "./img/eibsee.webp",
  },
  {
    name: "Landhaus Hotel Sommerau",
    projektart: "Basic",
    url: "https://www.landhaus-sommerau.de/",
    online: "04.04.2024",
    jahr: "2024",
    img: "./img/sommerau.webp",
  },
  {
    name: "Wirthshof",
    projektart: "Komfort",
    url: "https://www.wirthshof.de/",
    online: "28.11.2022",
    jahr: "2022",
    img: "./img/wirthshof.webp",
  },
  {
    name: "Leinsweiler Hof",
    projektart: "Komfort",
    url: "https://www.leinsweilerhof.de",
    online: "06.05.2024",
    jahr: "2024",
    img: "./img/leinsweiler.webp",
  },
  {
    name: "Hotel Restaurant Adler Oberstaufen",
    projektart: "Komfort",
    url: "https://adler-oberstaufen.de/",
    online: "08.02.2024",
    jahr: "2024",
    img: "./img/oberstaufen.webp",
  },
  {
    name: "Posthotel Erlerwirt",
    projektart: "Komfort",
    url: "https://www.posthotel-erlerwirt.at",
    online: "04.10.2022",
    jahr: "2022",
    img: "./img/erlerwirt.webp",
  },
  {
    name: "Gstaaderhof",
    projektart: "Komfort",
    url: "https://www.gstaaderhof.ch",
    online: "17.08.2022",
    jahr: "2022",
    img: "./img/gstaader.webp",
  },
  {
    name: "Hartungs Hoteldorf",
    projektart: "Komfort",
    url: "https://www.hartungs-hoteldorf.de/",
    online: "01.08.2022",
    jahr: "2022",
    img: "./img/hartungs.webp",
  },
  {
    name: "Kurpark Hotel Zinnowitz",
    projektart: "Basic",
    url: "https://www.zinnowitz-hotel.de",
    online: "09.11.2021",
    jahr: "2021",
    img: "./img/zinnowitz.webp",
  },
  {
    name: "Lumbergerhof",
    projektart: "Komfort",
    url: "https://www.lumbergerhof.at",
    online: "15.01.2022",
    jahr: "2022",
    img: "./img/lumbergerhof.webp",
  },
];
